# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Andre Aboulian
# tagline:          ''
# description:      ''
url:              http://aboolean.github.io
baseurl:          /

author:
  name:           'Andre Aboulian'
  url:            https://andreaboulian.com

avatar: https://avatars.githubusercontent.com/aboolean

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aboolean/aboolean.github.io