# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Andre Aboulian
# tagline:          ''
# description:      ''
url:              http://aboolean.github.io
baseurl:          /

author:
  name:           'Andre Aboulian'
  url:            https://andreaboulian.com

avatar: https://avatars.githubusercontent.com/aboolean

paginate:         5

links:
  github: https://github.com/aboolean/
  instagram: http://instagram.com/ab001ean
  facebook: http://facebook.com/andreaboulian
  flickr: http://flickr.com/andreaboulian
  linkedin: www.linkedin.com/in/andreaboulian

gems:
  - jemoji
